### PR TITLE
When checking if a transition is allowed, also check the custom Transition

### PR DESCRIPTION
**Pull request by powellblyth**
Hi, I find it annoying that a transition can fail even though canTransitionTo returns true, so I have updated canTransitionTo to include a check for that.

NOTE this PR has no tests yet, but I'm happy to commit that time if you are interested in this PR.

### CODE REVIEW

**Comment by brendt** [comment]
Can you give an example in code of what's this allows you to do?

**Comment by powellblyth** [comment]
Sure.
I have a transition
```

class ProducingTransition extends StatusTransition
{
    public function canTransition(): bool
    {
        // Can only transition to producing IF we are the next batch
        return $this->batch->isFirstBatch();
    }

    public function handle(): Batch
    {
        $this->batch->status = Batch::STATUS_PRODUCING;
        $this->batch->save();

        return $this->batch;
    }
}
```

which has this configuration
```
            ->allowTransition(AssignedToWorkStation::class, Producing::class, ProducingTransition::class)
```
Produciing class looks like this:
```
class Producing extends BatchStatus
{
    public static string $name = Batch::STATUS_PRODUCING;
}
```
so I run this:
```
if ($batch->status->CanTransitionTo::Batch::STATUS_PRODUCING)
{
   $batch->status->transitionTo(Batch::STATUS_PRODUCING);
}
```

But this produces the exception `TransitionNotAllowed`
because the `transition()` method does this
```
 if (method_exists($transition, 'canTransition')) {
            if (! $transition->canTransition()) {
                throw CouldNotPerformTransition::notAllowed($this->model, $transition);
            }
        }
```

but the canTransitionTo method does not

**Comment by BrianLangevin** [comment]
Seconding this. I'm using event sourcing to handle my state, so relying on an exception to determine whether a transition can occur is not ideal.

**Comment by brendt** [comment]
Gotcha, good one. Can you fix the tests and rebase your branch?

**Comment by powellblyth** [comment]
I've added the tests. I'm honestly not _so_ familiar with the whole codebase. I'm concerned that this will be a BC issue, since any code that relied on the 'old' method may suddenly start to fail.

I've had to make a couple of changes to other tests, since I got some errors either with my changes, or with making advantage of the existing dummies. 

Let me know what you think. You are more famiiliar with the ins and outs than me.

**Comment by brendt** [comment]
> I'm concerned that this will be a BC issue, since any code that relied on the 'old' method may suddenly start to fail.

I'd say it's a bug that should be fixed, I wouldn't treat it as breaking. Thanks for the PR, I'll merge and tag it.

**Comment by brendt** [comment]
Tagged: https://github.com/spatie/laravel-model-states/releases/tag/2.1.1

**Comment by powellblyth** [comment]
Hey @brendt  , I noticed that the transitionableStates method also doesn't check the custom transition. Would a PR for that be welcome?

```php
public function transitionableStates(string $fromMorphClass): array
    {
        $transitionableStates = [];

        foreach ($this->allowedTransitions as $allowedTransition => $value) {
            [$transitionFromMorphClass, $transitionToMorphClass] = explode('-', $allowedTransition);

            if ($transitionFromMorphClass !== $fromMorphClass) {
                continue;
            }

            $transitionableStates[] = $transitionToMorphClass;
        }

        return $transitionableStates;
    }
```

**Comment by brendt** [comment]
Yeah, that would be good, thanks!

**Pull request merged**
