### PR TITLE
[2.0] Update dependencies

### PR DESCRIPTION
**Pull request by mvdnbrk**
The `CastsAttributes` was introduced in Laravel 7 ([release note](https://laravel.com/docs/7.x/releases))
So L7.0 will be the minimum for V2.

Updated phpunit to the latest version 9.3, which comes with a config change in `phpunit.xml`.

### CODE REVIEW

**Comment by brendt** [comment]
We actually need `"laravel/framework": ^7.11` since that one introduced a bugfix for casters. Thanks!

**Comment by brendt** [comment]
I've changed it on the v2 branch btw

**Comment by mvdnbrk** [comment]
@brendt 👍 

I have updated `phpunit.xml` here (see https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-9.3.md#configuration-of-code-coverage-and-logging-in-phpunitxml for details)

So the minimum version of phpunit should be `^9.3`.

**Comment by brendt** [comment]
Gotcha, missed that one. Fixed it on v2

**Comment by mvdnbrk** [comment]
See #120 😉

**Pull request merged**
