### PR TITLE
Custom transitions same arguments

### PR DESCRIPTION
**Pull request by vytsci**
I do not know if this should be included, but I faced an issue when my custom transitions does not receive same arguments as DefaultTransition and I really needed those. So I came up with this solution. Please check this carefully, I will make fixed if needed or add more code to {$field}->transitionTo() as if used directly it wont have those arguments attached.

### CODE REVIEW

**Comment by brendt** [comment]
Could you provide an example of when you'd use this? Because the state passed to the transition also has a reference to the model, which you could expose if you'd want to. 

I think this PR would break usages of passing extra arguments to a transition: https://github.com/spatie/laravel-model-states/blob/87b888141d4a267f95af49d7a2777b9b7fb34442/src/State.php#L224

**Comment by vytsci** [comment]
I use this when I want to have a custom transition, but I need previous and next state known within that custom transition.

**Comment by vytsci** [comment]
It actually passes same parameters to default transition and they fit my needs. I thought maybe this is helpful.

**Comment by vytsci** [comment]
Ofc I can add reflection and check if custom transition for example extends DefaultTransition and only then pass those arguments.

**Comment by vytsci** [comment]
And I remembered the use case I needed, I just wanted to have single transition handling multiple states. I do not want to create transition for each state.

**Comment by brendt** [comment]
> I do not want to create transition for each state.

I think that's outside the scope of the current design. So I'm going to close this one for now. We might revisit it later.

**Pull request closed without merging**
