### PR TITLE
Add ignition solutions

### PR DESCRIPTION
**Pull request by travisobregon**
Hi @brendt,

I've opened this draft pull request if you would like to see how I have started. There is just one solution for unknown states at the moment.

### CODE REVIEW

**Comment by brendt** [comment]
Awesome, would you mind rebasing your branch on master? After that I'll review it.

**Comment by travisobregon** [comment]
Hi @brendt. It should be done now. Let me know if I have missed anything. Thanks.

**Comment by brendt** [comment]
Looking great, thanks!

**Comment by brendt** [comment]
Released as 1.4.0: https://github.com/spatie/laravel-model-states/releases/tag/1.4.0

**Pull request merged**
