### PR TITLE
Set getter attribute in TransitionNotFound

### PR DESCRIPTION
**Pull request by lloricode**
To make easily get current update when reach exception handler

 ```php
    // App\Exceptions\Handler
    public function render($request, Throwable $exception)
    {
        if ($request->expectsJson() && $exception instanceof TransitionNotFound) {

            $from = $exception->getFrom();
            $to = $exception->getTo();
            $model = $exception->getModelClass();

            $from = (new $from(new $model()))::$name;
            $to = (new $to(new $model()))::$name;

            $exception = new HttpException(
                Response::HTTP_UNPROCESSABLE_ENTITY,
                "Invalid transition from $from to $to.",
                $exception
            );
        }

        return parent::render($request, $exception);
    }
```

will result:
```
{
    "message": "Invalid transition from in-queue to in-queue.",
```

state class:
```php
<?php

namespace App\States\Orders;

class OrderInQueueState extends BaseOrderState
{
    public static $name = 'in-queue';

}
```

### CODE REVIEW

**Comment by brendt** [comment]
I think getters are a cleaner solution here, would you mind changing your PR?

**Comment by brendt** [comment]
Looks good, anything you'd like to change still, or is this good to merge from your side?

**Comment by lloricode** [comment]
> Looks good, anything you'd like to change still, or is this good to merge from your side?

@brendt it's good to go, thank you

**Comment by brendt** [comment]
Awesome, released as 1.8.0: https://github.com/spatie/laravel-model-states/releases/tag/1.8.0

**Pull request merged**
