### PR TITLE
V2

### PR DESCRIPTION
**Pull request by brendt**
Please read https://github.com/spatie/laravel-model-states/blob/v2/CHANGELOG.md#200--- for a changelog, we can still discuss and change some things.

### CODE REVIEW

**Comment by telkins** [comment]
The changes look good to me.  (I only read changlog.md.)  I can't imagine that it will take much time to update my existing code to work with this upgrade.  Looking forward to it...!  💪

**Comment by brendt** [comment]
@agentphoenix you can still check status-specific fields, instead of this:

```php
$model->canTransitionTo(StateB::class, 'status');
```

You can now do:

```php
$model->status->canTransitionTo(StateB::class);
```

**Comment by brendt** [comment]
> One thing I have felt is missing from this package is the ability to check the canTransition() method inside a transition class, to see if the logic passes, rather than just whether it is defined in the transition list. I understand there is limitation around this though.

@booni3 Not entirely sure I understood this correctly. Mind sharing an example?

**Comment by booni3** [comment]
@brendt sure:

We can easily check if the transition is in the allowTransition array, but if there is some more complicated logic within the transition class we still need to check this separately or wait for the transition error to be thrown.

```php
// Fulfilment.php
protected function registerStates(): void
{
    $this
        ->addState('state', FulfilmentState::class)
        ->allowTransition(Picked::class, Packed::class, ToPacked::class);
}

public function tryTransitionToPicked(): void
{
    // method does not currently exist
    if (! $this->canTransitionTo(Picked::class)) { 
        return; // Throw something here, or do something else
    }

   $this->transitionTo(Picked::class);
}
```

```php
// ToPacked.php
public function canTransition(): bool
{
    // check that all items have been picked
    return $this->fulfilment->picks->every(fn($row) => $row['allocated'] == $row['picked']); 
}
```

I know at the moment we can catch the transition exception but sometimes we need to be able to check this prior to actually making the transition. i.e. showing a "To Packed" button conditionally.

My canTransitionTo() method currently looks like this (I realise this is messy!):

```php
public function canTransitionTo(string $toClass, $field = 'state'): bool
{
    $stateConfig = self::getStateConfig();
    $stateClass = $stateConfig[$field]->stateClass;

    try {
        $transition = $this->resolveTransitionClass(
            $stateClass::resolveStateClass($this->{$field}),
            $stateClass::resolveStateClass($toClass)
        );

        if($transition instanceof DefaultTransition){
            return $transition->canTransition();
        }

        if (method_exists(app($transition), 'canTransition')) {
            $params = (new \ReflectionClass(get_class(app($transition))))->getConstructor()->getParameters();
            foreach($params as $key => $param){
                if($key > 0){
                    if(! is_null($param->getDefaultValue())){
                        throw new \Exception('Any additional constructor arguments after the model must be null');
                    }
                }
            }

            return app()
                ->makeWith($transition, [$params[0]->name => $this])
                ->canTransition();
        }
    } catch (TransitionNotFound $e) {
        // do nothing
    }

    return in_array($toClass, $this->state->transitionableStates($field));
}
```

**Comment by mvdnbrk** [comment]
In Laravel 8, the `Illuminate\Contracts\Database\Eloquent\Castable` changed from:

```php
public static function castUsing();
```
to 

```php
public static function castUsing(array $arguments);
```
That's the reason why tests are failing now.

**Comment by brendt** [comment]
Yeah, that probably means v2 will only support L8, this is still WIP anyways

**Comment by mvdnbrk** [comment]
@brendt 👍 Let me know if I can help with making those changes.

**Comment by brendt** [comment]
Here's an update:

- Equals now also accepts morph names, there are indeed good use cases for them
- All v1 functionality is ported to this branch, with as little breaking changes as possible
- I plan to merge and tag this soon, feel free to provide feedback if you want in the coming days

**Review by lloricode — APPROVED** [review]

**Comment by lloricode** [comment]
> Proper support for finalState in StateChanged event

I'm looking forward this this

**Comment by lloricode** [comment]
Hi!, just checking around for update :1234:

**Comment by ju5t** [comment]
Should we still get an array of strings instead of objects with `getStatesFor('state')` in v2?

```php
Illuminate\Support\Collection {#1464 ▼
  #items: array:6 [▼
    0 => "Domain\Quotes\States\Accepted"
    1 => "Domain\Quotes\States\Concept"
    2 => "Domain\Quotes\States\Expired"
    3 => "Domain\Quotes\States\Pending"
    4 => "Domain\Quotes\States\RFQ"
    5 => "Domain\Quotes\States\Sent"
  ]
}
```

I was hoping there would be a simple way to get all possible states as objects. Am I missing something or is this not supported in v2?

**Comment by brendt** [comment]
Ok so I've been rather busy with a project that's coming to an end now. I'll come back to this soon!

**Comment by brendt** [comment]
> I was hoping there would be a simple way to get all possible states as objects.

@ju5t you can't instantiate state objects without the model and state config: `public function __construct(Model $model, StateConfig $stateConfig)`

It's the model that's problematic, since you'd use the `getStatesFor` method in a static context, there's no model object we could use.

**Comment by ju5t** [comment]
> It's the model that's problematic, since you'd use the `getStatesFor` method in a static context, there's no model object we could use.

I've added a `states` attribute to the models that use state as a workaround.

```
public function getStatesAttribute()
{
    $states = [];

    foreach ($this->getStatesFor('state') as $state) {
        $states[$state] = call_user_func($state.'::label');
    }

    return $states;
}
```

It's OK enough for now. It helps with dropdowns although I have to do some juggling as we prefer not to leak our class names to our rendered HTML. I do wonder how others do this but I guess that's out of scope for this issue 😄

**Comment by brendt** [comment]
Hi everyone. I realise this I'm rather late with this followup, but things got rather busy over the past weeks.

Anyway, I've finally managed to try out v2 myself in one of our projects. There's one rather large issue with it though, and I'd like to discuss possible solutions.

With v2, our aim was to have the state class internally know about how it was configured on the model. This makes it possible to do this:

```php
$model->status->canTransitionTo(StateB::class);
```

Instead of this:

```php
$model->canTransitionTo(StateB::class, 'status');
```

The reason for this is because previously, the state class itself didn't know what field it belonged to on the model, and thus wasn't able to figure out what specific configuration was used for that state. V2 solves this by providing not only the model instance, but also the state config to a state object when it's constructed: 

```php
    public function __construct(Model $model, StateConfig $stateConfig)
    {
        $this->model = $model;
        $this->stateConfig = $stateConfig;
    }
```

This is where the trouble starts: we're not able to construct state objects anymore "out of the blue" we now not only need a model, but also a `StateConfig` on top of that!

That results in stuff like `MyState::make('value', $model)` not working anymore; and also makes it impossible to do something like `MyState::all()` and return concrete instances.

I think v2 should properly solve those issues. So I was thinking, what if we wouldn't need to provide the state config from outside? What if the state instead knew about its config all along?  In other words: configure state classes from within themselves, instead of via the model? That would look something like this:

```php
abstract class ModelState extends State
{
    public function __construct(Model $model)
    {
        parent::__construct($model);
        
        $this
            ->allowTransition(StateA::class, StateB::class)
            ->allowTransition(StateA::class, StateC::class)
            ->allowTransition(StateA::class, StateD::class)
            ->defaultState(StateA::class);
    }
}
```

Now, there's one downside to this approach: we're linking states and their config directly together. Right now there's the flexibility of using the same state object for different fields, with different configs. That wouldn't be possible anymore. In those cases you'd actually make separate state classes with separate configs. Is that so bad though? A colleague and myself looked at the two projects we're using this package in, both making abundant use of states; and we never once had a scenario where we wanted to reuse a state class with different configs. 

So this is up for debate now: do you think this is the right approach? 

One more nicety we could add in the future: attribute support. Instead of writing the state constructor, you could do something like this:

```php
#[
    AllowTransition(StateA::class, StateB::class),
    DefaultState(StateA::class),
]
abstract class ModelState extends State
{
}
```

I won't add attributes in v2 though, it might be a feature release down the line.

Looking forward to hear your feedback!

**Comment by brendt** [comment]
FYI I pushed the latest changes to this branch.

**Comment by brendt** [comment]
Todo:

- [ ] Add `make` again
- [ ] Update docs

**Comment by lloricode** [comment]
Hi @brendt!,

working expected on our side after upgrading to version 2, I just notice with `TransitionNotFound`, is it possible to add what column of model are being use? incase want to manipulate specific state class, because we have multiple state column one of our model.

Great Thanks of this wonderful package

**Comment by brendt** [comment]
I went ahead and added optional attribute support if you're using PHP 8. What do you think?

Screen Shot 2020-11-26 at 13 39 38

Screen Shot 2020-11-26 at 13 39 28

**Pull request merged**
